## Project description
*The content of the text below was written long time ago. It should be reviewed and updated*  

#### Experimental measurement of Dung Removal rate on a worldwide scale

Dung beetles are key components for the functioning of many ecosystems, as they
are involved in several ecosystem services due to their roll in dung removal. Dung
removal is a very important process for the functioning of ecosystems as it improves the
nutrient cycling, bioturbation, seed dispersal, plant growth, and parasite regulation. It is
usually assumed that functional diversity (i.e. the diversity of the organismal traits that
influence ecosystem functioning) and certain traits are directly linked to ecosystem
functioning. In this multi-site experiment we want to study the relationship between
dung removal rates and the functional composition of dung beetle assemblages in
different grasslands around the world. We expect that the composition of dung beetle
assemblages, and in particular the composition in terms of functional groups based on
dung processing behavior (dwellers, tunnellers and rollers vs. big, medium and small
sizes), will be related to dung removal efficiency.  

Land use changes are one of the main agents of global change. The progressive
intensification of human-related activities can negatively affect the diversity of local
communities and of the ecosystem services they provide. In this project we will also
consider different levels of land management, evaluating the effects of land use
intensification on the diversity of dung beetle assemblages and on the rates of dung
removal. We expect that grasslands with lower management intensity (less amount of
cattle per area) will have a more complex assemblage structure, higher diversity and
dung removal rates.  

The added value of working at this large scale is the inclusion of a wide range of
climates, evolutionary histories and human impacts. This will also allow evaluating
whether latitudinal changes will have an impact on this process and on dung beetle
assemblage composition. We expect that dung beetle functional diversity, abundance,
richness and biomass will show the typical latitudinal gradient, with higher diversity
towards the tropics; such gradient should affect dung removal rates. Confounding
factors like herbivores and habitat type, and dung pad size will be controlled for as
much as possible, by using size- and volume-controlled dung pads of one herbivore
species in a grassland environment.  

In summary, in this project, we propose a sampling protocol that will be used in a
worldwide experiment with multiple sites in different biogeographical and climatic
regions. Such protocol will allow evaluating the following research questions:
* (i) Is there a relationship between dung removal and dung beetle assemblage structure?  
* (ii) Does cattle management intensity affect dung removal?  
* (iii) Are these patterns similar or different around the world?
